name: "ğŸ›  Release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-11]

    runs-on: ${{ matrix.os }}
    steps:
      - name: "ğŸ”½ Checking out code"
        uses: actions/checkout@v3
      - name: "ğŸ Installing Python"
        uses: actions/setup-python@v4
        with:
          # Matches Blender 3.4.1 Python version
          python-version: "3.10"
          cache: "pip"
      - name: "ğŸ“¦ Packaging Dependencies"
        run: python package.py
      - name: "ğŸŠ Making the release"
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.zip
